
/**
 * Cache optimization configuration
 * Auto-generated by scripts/generate-cache-config.js
 */

// Headers configuration for optimal caching
const cacheHeaders = [
  {
    "source": "/fonts/:path*.woff",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/fonts/:path*.woff2",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/fonts/:path*.ttf",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/fonts/:path*.otf",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/:path*.ico",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/:path*.webmanifest",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/icons/:path*.webp",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/icons/:path*.png",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/icons/:path*.jpg",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/icons/:path*.jpeg",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/icons/:path*.gif",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/icons/:path*.svg",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/images/:path*.webp",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/images/:path*.png",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/images/:path*.jpg",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/images/:path*.jpeg",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/images/:path*.gif",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/images/:path*.svg",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/blog/:path*.webp",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/blog/:path*.png",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/blog/:path*.jpg",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/blog/:path*.jpeg",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/blog/:path*.gif",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/blog/:path*.svg",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=86400, stale-while-revalidate=31536000"
      }
    ]
  },
  {
    "source": "/_next/static/:path*.js",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/_next/static/:path*.css",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=31536000, immutable"
      }
    ]
  },
  {
    "source": "/:path*.html",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=0, must-revalidate"
      }
    ]
  },
  {
    "source": "/_next/data/:path*.json",
    "headers": [
      {
        "key": "Cache-Control",
        "value": "public, max-age=0, must-revalidate"
      }
    ]
  }
];

// Export the cache headers for use in next.config.js
module.exports = {
  cacheHeaders
};
