
import React from 'react';

// This component was auto-generated by the optimize-fonts.js script
// It creates preload links for fonts to improve loading performance
export default function FontPreload() {
  return (
    <>
      <link
        rel="preload"
        href="/fonts/inter-var.woff2"
        as="font"
        type="font/woff2"
        crossOrigin="anonymous"
        
      />
    </>
  );
}
