#!/usr/bin/env node
/**
 * Font Optimization Script
 * 
 * This script analyzes font usage in the project and generates optimized preload directives
 * for critical fonts to improve loading performance.
 */

const fs = require('fs');
const path = require('path');
const glob = require('glob');

// Configuration
const CONFIG = {
  fontExtensions: ['.woff2', '.woff', '.ttf', '.otf'],
  fontDir: 'public/fonts',
  outputFile: 'app/components/FontPreload.tsx',
  priorityFonts: [
    // List your most important fonts here (used in above-the-fold content)
    'Inter-Regular',
    'Inter-Medium',
    'Inter-Bold'
  ]
};

/**
 * Find all fonts in the font directory
 */
function findFonts() {
  const fontPaths = [];
  
  // Make sure the font directory exists
  if (!fs.existsSync(path.resolve(process.cwd(), CONFIG.fontDir))) {
    console.log(`⚠️ Font directory '${CONFIG.fontDir}' not found. Creating it...`);
    fs.mkdirSync(path.resolve(process.cwd(), CONFIG.fontDir), { recursive: true });
    return fontPaths;
  }
  
  // Find all font files with supported extensions
  CONFIG.fontExtensions.forEach(ext => {
    const files = glob.sync(path.join(CONFIG.fontDir, `**/*${ext}`));
    fontPaths.push(...files);
  });
  
  return fontPaths;
}

/**
 * Generate the font preload component
 */
function generateFontPreloadComponent(fonts) {
  if (fonts.length === 0) {
    return `
import React from 'react';

// No fonts found to preload
export default function FontPreload() {
  return null;
}
`;
  }

  // Determine font type by extension
  const getFontType = (filePath) => {
    const ext = path.extname(filePath).toLowerCase();
    switch (ext) {
      case '.woff2': return 'font/woff2';
      case '.woff': return 'font/woff';
      case '.ttf': return 'font/ttf';
      case '.otf': return 'font/otf';
      default: return 'font/woff2';
    }
  };

  // Generate code for the component
  const preloadLinks = fonts.map(font => {
    const relativePath = font.replace('public', '');
    const fontName = path.basename(font, path.extname(font));
    const fontType = getFontType(font);
    const isPriority = CONFIG.priorityFonts.some(priorityFont => fontName.includes(priorityFont));
    
    return `      <link
        rel="preload"
        href="${relativePath}"
        as="font"
        type="${fontType}"
        crossOrigin="anonymous"
        ${isPriority ? 'importance="high"' : ''}
      />`;
  }).join('\n');

  return `
import React from 'react';

// This component was auto-generated by the optimize-fonts.js script
// It creates preload links for fonts to improve loading performance
export default function FontPreload() {
  return (
    <>
${preloadLinks}
    </>
  );
}
`;
}

/**
 * Generate font-display CSS
 */
function generateFontDisplayCSS() {
  return `
/* Font optimization - Apply font-display to all @font-face rules */
@layer base {
  @font-face {
    font-display: swap;
  }
}
`;
}

/**
 * Process all fonts and create the preload component
 */
function main() {
  console.log('🔍 Scanning for fonts...');
  const fonts = findFonts();
  
  if (fonts.length === 0) {
    console.log('⚠️ No fonts found. Create a "public/fonts" directory and add your font files.');
  } else {
    console.log(`✅ Found ${fonts.length} font files`);
  }
  
  // Generate and save preload component
  const preloadComponent = generateFontPreloadComponent(fonts);
  const outputPath = path.resolve(process.cwd(), CONFIG.outputFile);
  
  // Create directory if it doesn't exist
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  
  fs.writeFileSync(outputPath, preloadComponent);
  console.log(`✅ Created font preload component at: ${CONFIG.outputFile}`);
  
  // Add font-display to global CSS if it exists
  try {
    const globalCssPath = path.resolve(process.cwd(), 'app/globals.css');
    if (fs.existsSync(globalCssPath)) {
      let cssContent = fs.readFileSync(globalCssPath, 'utf8');
      
      // Only add if not already there
      if (!cssContent.includes('font-display: swap')) {
        cssContent += generateFontDisplayCSS();
        fs.writeFileSync(globalCssPath, cssContent);
        console.log('✅ Updated globals.css with font-display optimization');
      } else {
        console.log('ℹ️ font-display optimization already present in globals.css');
      }
    }
  } catch (error) {
    console.error('⚠️ Error updating globals.css:', error.message);
  }
  
  console.log('✨ Font optimization complete!');
}

main(); 